# this is for creating the tariffs and save them in the json file the json file then can be read from the API
import json
import io
import os

AllTariffs = [{"Tariff ID": "T00001",
               "Provider": "AGL",
               "Type": "Flat_rate",
               "State": "NSW",
               "Name": "AGL Flat Rate Residential",
               "Year": "2017/18",
               "Discount (%)": 14,
               "Tariff Code": "AGL366956MR",
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 0.924, "Unit": "$/day"},
                              "Energy":
                                  {"Value": 0.319, "Unit": "$/kWh"},
                              "FiT":
                                  {"Value": 0.111, "Unit": "$/kWh"}}},
              {"Tariff ID": "T00002",
               "Provider": "Energy Australia",
               "Type": "Flat_rate",
               "State": "NSW",
               "Name": "Energy Australia Flat Rate Residential",
               "Year": "2017/18",
               "Discount (%)": 12,
               "Tariff Code": "ENE390950MR",
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 0.9251, "Unit": "$/day"},
                              "Energy":
                                  {"Value": 0.32285, "Unit": "$/kWh"},
                              "FiT":
                                  {"Value": 0.125, "Unit": "$/kWh"}}},
              {"Tariff ID": "T00003",
               "Provider": "Origin Energy",
               "Type": "Flat_rate",
               "State": "NSW",
               "Name": " Origin Energy Flat Rate Residential",
               "Year": "2017/18",
               "Discount (%)": 22,
               "Tariff Code": "ORI402604MR",
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 0.91729, "Unit": "$/day"},
                              "Energy":
                                  {"Value": 0.31372, "Unit": "$/kWh"},
                              "FiT":
                                  {"Value": 0.09, "Unit": "$/kWh"}}},
              {"Tariff ID": "T00004",
               "Provider": "AGL",
               "Type": "TOU",
               "State": "NSW",
               "Name": " AGL TOU Residential",
               "Year": "2017/18",
               "Discount (%)": 14,
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 1.056, "Unit": "$/day"},
                              "Energy": {'Peak': {"Value": 0.594, "Unit": "$/kWh",
                                                  "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                  "Weekday": True, "Weekend": False,
                                                  "TimeIntervals": {'T1': ['14:00', '20:00']}},
                                         'Shoulder 1': {"Value": 0.253, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": True, "Weekend": False,
                                                        "TimeIntervals": {'T1': ['07:00', '14:00'],
                                                                          'T2': ['20:00', '22:00']}},
                                         'Shoulder 2': {"Value": 0.253, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": False, "Weekend": True,
                                                        "TimeIntervals": {'T1': ['07:00', '22:00']}},
                                         'Off Peak': {"Value": 0.165, "Unit": "$/kWh",
                                                      "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                      "Weekday": True, "Weekend": True,
                                                      "TimeIntervals": {'T1': ['00:00', '07:00'],
                                                                        'T2': ['22:00', '24:00']}}},
                              "FiT": {"Value": 0.111, "Unit": "$/kWh"}}},
              {"Tariff ID": "T00005",
               "Provider": "Energy Australia",
               "Type": "TOU",
               "State": "NSW",
               "Name": " Energy Australia TOU Residential",
               "Year": "2017/18",
               "Discount (%)": 12,
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 1.0604, "Unit": "$/day"},
                              "Energy": {'Peak': {"Value": 0.6039, "Unit": "$/kWh",
                                                  "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                  "Weekday": True, "Weekend": False,
                                                  "TimeIntervals": {'T1': ['14:00', '20:00']}},
                                         'Shoulder 1': {"Value": 0.27456, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": True, "Weekend": False,
                                                        "TimeIntervals": {'T1': ['07:00', '14:00'],
                                                                          'T2': ['20:00', '22:00']}},
                                         'Shoulder 2': {"Value": 0.27456, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": False, "Weekend": True,
                                                        "TimeIntervals": {'T1': ['07:00', '22:00']}},
                                         'Off Peak': {"Value": 0.16764, "Unit": "$/kWh",
                                                      "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                      "Weekday": True, "Weekend": True,
                                                      "TimeIntervals": {'T1': ['00:00', '07:00'],
                                                                        'T2': ['22:00', '24:00']}}},
                              "FiT": {"Value": 0.125, "Unit": "$/kWh"}}},
               {"Tariff ID": "T00006",
               "Provider": "Origin Energy",
               "Type": "TOU",
               "State": "NSW",
               "Name": " Origin Energy TOU Residential",
               "Year": "2017/18",
               "Discount (%)": 22,
               "ProviderType": "Retailer",
               "Distributor": "Ausgrid",
               "Parameters": {"Daily":
                                  {"Value": 1.06535, "Unit": "$/day"},
                              "Energy": {'Peak': {"Value": 0.58311, "Unit": "$/kWh",
                                                  "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                  "Weekday": True, "Weekend": False,
                                                  "TimeIntervals": {'T1': ['14:00', '20:00']}},
                                         'Shoulder 1': {"Value": 0.26169, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": True, "Weekend": False,
                                                        "TimeIntervals": {'T1': ['07:00', '14:00'],
                                                                          'T2': ['20:00', '22:00']}},
                                         'Shoulder 2': {"Value": 0.26169, "Unit": "$/kWh",
                                                        "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                        "Weekday": False, "Weekend": True,
                                                        "TimeIntervals": {'T1': ['07:00', '22:00']}},
                                         'Off Peak': {"Value": 0.15862, "Unit": "$/kWh",
                                                      "Month": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                                      "Weekday": True, "Weekend": True,
                                                      "TimeIntervals": {'T1': ['00:00', '07:00'],
                                                                        'T2': ['22:00', '24:00']}}},
                              "FiT": {"Value": 0.09, "Unit": "$/kWh"}}}
                  ]
AllTariffs = json.dumps(AllTariffs)
# to_unicode = str
with io.open(os.path.join('D:\\Codes\\Tariff-API\\application', 'AllTariffs.json'), 'w', encoding='utf8') as outfile:
    outfile.write(str(AllTariffs))